# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa4359512b1633106c752dc121e5ece07b91ddf5f01d636226a3f5857e068cab424567cc7f4b11739edc8834519eda88327cd69a278bfb7ce83db8cfc38377a9

test:
  secret_key_base: b377c14366b6820f10f643c02fc8f264789b5d1fec7b5518d72dce53d5e29b9bdf74081c465d83beaf603e63cb6f7429ce2536056e5c16d50e2cec90205bfa5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
